# Built with Jekyll 3.2.0

# Setup
title:               'U.S. Semantic Technologies Symposium Series'
editiontitle:        '3rd U.S. Semantic Technologies Symposium'
location:            'North Carolina State University, Raleigh, NC'
date:                'March 9-11, 2020'
description:         'Annual conference for the North-American Semantic Web community'
url:                 'http://us2ts.org'
logo:                'us2ts_color.png'
baseurl:             ''

# About/contact
author:
  name:              Maulik R. Kamdar
  url:               https://twitter.com/maulikkamdar
  email:             maulikrk@stanford.edu

# Google Analytics
google_analytics:    'UA-150938475-1'

# Color scheme. Options: red, orange, magenta, cyan, blue, brown
color-scheme: orange

# Permalinks
permalink: pretty
permalink: /:title/

# Set encoding to UTF-8
encoding: utf-8

# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor
  - Gemfile
  - Gemfile.lock
  - serve-local.sh
  - README.md

plugins:
#  - jekyll-last-modified-at

# Theme
#theme: "ed."
